# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: membrane/disagg/transfer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'membrane/disagg/transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emembrane/disagg/transfer.proto\x12\x0fmembrane.disagg\"\x91\x01\n\x0ePrefillRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x11\n\ttoken_ids\x18\x03 \x03(\x03\x12\x16\n\x0etoken_type_ids\x18\x04 \x03(\x03\x12\x19\n\x11max_decode_tokens\x18\x05 \x01(\x05\x12\x13\n\x0b\x66ingerprint\x18\x06 \x01(\t\"{\n\x0fPrefillResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tkv_handle\x18\x02 \x01(\t\x12\x12\n\nprefill_ms\x18\x03 \x01(\x01\x12\x12\n\nprompt_len\x18\x04 \x01(\x05\x12\x19\n\x11\x63\x61\x63hed_prefix_len\x18\x05 \x01(\x05\"H\n\x13\x42\x61tchPrefillRequest\x12\x31\n\x08requests\x18\x01 \x03(\x0b\x32\x1f.membrane.disagg.PrefillRequest\"_\n\x14\x42\x61tchPrefillResponse\x12\x33\n\tresponses\x18\x01 \x03(\x0b\x32 .membrane.disagg.PrefillResponse\x12\x12\n\nelapsed_ms\x18\x02 \x01(\x01\"\\\n\rDecodeRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tkv_handle\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\"I\n\x0e\x44\x65\x63odeResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttoken_ids\x18\x02 \x03(\x03\x12\x10\n\x08\x66inished\x18\x03 \x01(\x08\x32\x80\x02\n\x08Transfer\x12L\n\x07Prefill\x12\x1f.membrane.disagg.PrefillRequest\x1a .membrane.disagg.PrefillResponse\x12[\n\x0c\x42\x61tchPrefill\x12$.membrane.disagg.BatchPrefillRequest\x1a%.membrane.disagg.BatchPrefillResponse\x12I\n\x06\x44\x65\x63ode\x12\x1e.membrane.disagg.DecodeRequest\x1a\x1f.membrane.disagg.DecodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'membrane.disagg.transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREFILLREQUEST']._serialized_start=52
  _globals['_PREFILLREQUEST']._serialized_end=197
  _globals['_PREFILLRESPONSE']._serialized_start=199
  _globals['_PREFILLRESPONSE']._serialized_end=322
  _globals['_BATCHPREFILLREQUEST']._serialized_start=324
  _globals['_BATCHPREFILLREQUEST']._serialized_end=396
  _globals['_BATCHPREFILLRESPONSE']._serialized_start=398
  _globals['_BATCHPREFILLRESPONSE']._serialized_end=493
  _globals['_DECODEREQUEST']._serialized_start=495
  _globals['_DECODEREQUEST']._serialized_end=587
  _globals['_DECODERESPONSE']._serialized_start=589
  _globals['_DECODERESPONSE']._serialized_end=662
  _globals['_TRANSFER']._serialized_start=665
  _globals['_TRANSFER']._serialized_end=921
# @@protoc_insertion_point(module_scope)
