# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from membrane.transport.proto import membrane_pb2 as membrane__pb2

GRPC_GENERATED_VERSION = "1.82.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in membrane_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MembraneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreFragment = channel.unary_unary(
            "/membrane.Membrane/StoreFragment",
            request_serializer=membrane__pb2.StoreRequest.SerializeToString,
            response_deserializer=membrane__pb2.StoreResponse.FromString,
            _registered_method=True,
        )
        self.RetrieveFragment = channel.unary_unary(
            "/membrane.Membrane/RetrieveFragment",
            request_serializer=membrane__pb2.RetrieveRequest.SerializeToString,
            response_deserializer=membrane__pb2.RetrieveResponse.FromString,
            _registered_method=True,
        )
        self.SyncInventory = channel.unary_unary(
            "/membrane.Membrane/SyncInventory",
            request_serializer=membrane__pb2.InventoryRequest.SerializeToString,
            response_deserializer=membrane__pb2.InventoryResponse.FromString,
            _registered_method=True,
        )
        self.Prefill = channel.unary_unary(
            "/membrane.Membrane/Prefill",
            request_serializer=membrane__pb2.PrefillRequest.SerializeToString,
            response_deserializer=membrane__pb2.PrefillResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/membrane.Membrane/Heartbeat",
            request_serializer=membrane__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=membrane__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )


class MembraneServicer:
    """Missing associated documentation comment in .proto file."""

    def StoreFragment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RetrieveFragment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SyncInventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Prefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MembraneServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StoreFragment": grpc.unary_unary_rpc_method_handler(
            servicer.StoreFragment,
            request_deserializer=membrane__pb2.StoreRequest.FromString,
            response_serializer=membrane__pb2.StoreResponse.SerializeToString,
        ),
        "RetrieveFragment": grpc.unary_unary_rpc_method_handler(
            servicer.RetrieveFragment,
            request_deserializer=membrane__pb2.RetrieveRequest.FromString,
            response_serializer=membrane__pb2.RetrieveResponse.SerializeToString,
        ),
        "SyncInventory": grpc.unary_unary_rpc_method_handler(
            servicer.SyncInventory,
            request_deserializer=membrane__pb2.InventoryRequest.FromString,
            response_serializer=membrane__pb2.InventoryResponse.SerializeToString,
        ),
        "Prefill": grpc.unary_unary_rpc_method_handler(
            servicer.Prefill,
            request_deserializer=membrane__pb2.PrefillRequest.FromString,
            response_serializer=membrane__pb2.PrefillResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=membrane__pb2.HeartbeatRequest.FromString,
            response_serializer=membrane__pb2.HeartbeatResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("membrane.Membrane", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("membrane.Membrane", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Membrane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreFragment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/membrane.Membrane/StoreFragment",
            membrane__pb2.StoreRequest.SerializeToString,
            membrane__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RetrieveFragment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/membrane.Membrane/RetrieveFragment",
            membrane__pb2.RetrieveRequest.SerializeToString,
            membrane__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SyncInventory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/membrane.Membrane/SyncInventory",
            membrane__pb2.InventoryRequest.SerializeToString,
            membrane__pb2.InventoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Prefill(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/membrane.Membrane/Prefill",
            membrane__pb2.PrefillRequest.SerializeToString,
            membrane__pb2.PrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/membrane.Membrane/Heartbeat",
            membrane__pb2.HeartbeatRequest.SerializeToString,
            membrane__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
