# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from membrane.wire.v3 import wire_v3_pb2 as membrane_dot_wire_dot_v3_dot_wire__v3__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in membrane/wire/v3/wire_v3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransferStub:
    """Service: bidi stream for resumable + authenticated transfer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.stream_stream(
                '/membrane.wire.v3.Transfer/Open',
                request_serializer=membrane_dot_wire_dot_v3_dot_wire__v3__pb2.ChunkRequest.SerializeToString,
                response_deserializer=membrane_dot_wire_dot_v3_dot_wire__v3__pb2.Chunk.FromString,
                _registered_method=True)


class TransferServicer:
    """Service: bidi stream for resumable + authenticated transfer.
    """

    def Open(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.stream_stream_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=membrane_dot_wire_dot_v3_dot_wire__v3__pb2.ChunkRequest.FromString,
                    response_serializer=membrane_dot_wire_dot_v3_dot_wire__v3__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'membrane.wire.v3.Transfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('membrane.wire.v3.Transfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transfer:
    """Service: bidi stream for resumable + authenticated transfer.
    """

    @staticmethod
    def Open(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/membrane.wire.v3.Transfer/Open',
            membrane_dot_wire_dot_v3_dot_wire__v3__pb2.ChunkRequest.SerializeToString,
            membrane_dot_wire_dot_v3_dot_wire__v3__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
