# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: membrane/wire/v3/wire_v3.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'membrane/wire/v3/wire_v3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emembrane/wire/v3/wire_v3.proto\x12\x10membrane.wire.v3\"\xb5\x01\n\x08\x45nvelope\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x1a\n\x12\x66ingerprint_compat\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_hash\x18\x05 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x06 \x01(\x03\x12\x13\n\x0b\x63ompression\x18\x07 \x01(\x05\x12\x14\n\x0c\x63ontent_type\x18\x08 \x01(\t\"W\n\rTensorPayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x1a\n\x12schema_fingerprint\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\r\n\x05\x64type\x18\x04 \x01(\t\"C\n\x0c\x43hunkRequest\x12\x13\n\x0b\x63hunk_index\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0e\n\x06length\x18\x03 \x01(\x03\"_\n\x05\x43hunk\x12\x13\n\x0b\x63hunk_index\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x12\n\nsha256_hex\x18\x04 \x01(\t\x12\x0f\n\x07is_last\x18\x05 \x01(\x08\x32O\n\x08Transfer\x12\x43\n\x04Open\x12\x1e.membrane.wire.v3.ChunkRequest\x1a\x17.membrane.wire.v3.Chunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'membrane.wire.v3.wire_v3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=53
  _globals['_ENVELOPE']._serialized_end=234
  _globals['_TENSORPAYLOAD']._serialized_start=236
  _globals['_TENSORPAYLOAD']._serialized_end=323
  _globals['_CHUNKREQUEST']._serialized_start=325
  _globals['_CHUNKREQUEST']._serialized_end=392
  _globals['_CHUNK']._serialized_start=394
  _globals['_CHUNK']._serialized_end=489
  _globals['_TRANSFER']._serialized_start=491
  _globals['_TRANSFER']._serialized_end=570
# @@protoc_insertion_point(module_scope)
