"""Compatibility re-exports; the routes live in :mod:`membrane.transport.routes`."""

from membrane.transport.ops import MAX_BODY_BYTES
from membrane.transport.routes import register_routes
from membrane.transport.routes.cluster import (
    handle_gossip,
    handle_join,
    handle_leave,
    handle_peers,
    handle_replicate,
)
from membrane.transport.routes.common import (
    auth_error_response,
    authenticator_for,
    peer_headers,
    read_limited_body,
    respond,
    respond_with_retry_after,
    route_scope,
    transport_metrics_for,
)
from membrane.transport.routes.data import (
    handle_get_blob,
    handle_inventory,
    handle_prefill,
    handle_put_blob,
    handle_retrieve,
    handle_store,
    handle_sync,
)
from membrane.transport.routes.deletes import (
    handle_delete,
    handle_purge,
    handle_tombstone,
    handle_verify,
)
from membrane.transport.routes.models import (
    DeleteRequest,
    FragmentPayload,
    GossipRequest,
    JoinRequest,
    LeaveRequest,
    PrefillRequest,
    PurgeRequest,
    ReplicateRequest,
    StoreRequest,
    SyncRequest,
    TombstoneRequest,
    VerifyRequest,
)
from membrane.transport.routes.probes import (
    handle_heartbeat,
    handle_metrics,
    livez,
    metrics_json,
    readyz,
)

__all__ = [
    "MAX_BODY_BYTES",
    "DeleteRequest",
    "FragmentPayload",
    "GossipRequest",
    "JoinRequest",
    "LeaveRequest",
    "PrefillRequest",
    "PurgeRequest",
    "ReplicateRequest",
    "StoreRequest",
    "SyncRequest",
    "TombstoneRequest",
    "VerifyRequest",
    "auth_error_response",
    "authenticator_for",
    "handle_delete",
    "handle_get_blob",
    "handle_gossip",
    "handle_heartbeat",
    "handle_inventory",
    "handle_join",
    "handle_leave",
    "handle_metrics",
    "handle_peers",
    "handle_prefill",
    "handle_purge",
    "handle_put_blob",
    "handle_replicate",
    "handle_retrieve",
    "handle_store",
    "handle_sync",
    "handle_tombstone",
    "handle_verify",
    "livez",
    "metrics_json",
    "peer_headers",
    "read_limited_body",
    "readyz",
    "register_routes",
    "respond",
    "respond_with_retry_after",
    "route_scope",
    "transport_metrics_for",
]
